config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'products#index'
  namespace :admin do
    resources :products
  end
  resources :products do
    resources :cart_products, only: :create
  end
  resources :cart_products, only: %i[index update destroy]
  resources :carts do
    resources :orders, only: %i[create show]
  end
  resources :orders, only: %i[index]
  resources :promotions, only: %i[update]
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/cart_product.rb
# frozen_string_literal: true

class CartProduct < ApplicationRecord
  belongs_to :cart
  belongs_to :product
  validates :quantity, presence: true,
                       numericality: { only_integer: true, greater_than_or_equal_to: 0, message: 'を0以上の半角数字で入力してください' }
end

app/controllers/cart_products_controller.rb
# frozen_string_literal: true

class CartProductsController < ApplicationController
  before_action :load_cart_product, only: %i[update destroy]

  def index
    @order = Order.new
    return unless @current_cart.promotion

    @discounted_price = [@current_cart.cart_products.sum(:total_price) - @current_cart.promotion.discount_price,
                         0].max
  end

  def create
    product = Product.find(cart_product_create_params[:product_id])
    quantity = (cart_product_create_params[:quantity].presence || 1).to_i
    cart_product = CartProduct.find_or_initialize_by(cart_id: @current_cart.id, product_id: product.id)
    cart_product.name = product.name
    cart_product.price = product.price
    cart_product.quantity = cart_product.quantity.to_i + quantity
    cart_product.total_price = calculate_price(product, cart_product.quantity)

    save_and_redirect(cart_product, cart_product.new_record? ? '商品をカートに追加しました。' : '数量を更新しました。', root_path)
  end

  def update
    quantity = cart_product_update_params[:quantity].to_i
    if quantity < 1
      destroy_cart_product
    else
      @cart_product.quantity = quantity
      @cart_product.total_price = calculate_price(@cart_product, quantity)
      save_and_redirect(@cart_product, '数量を更新しました。', cart_products_path)
    end
  end

  def destroy
    destroy_cart_product
  end

  private

  def cart_product_create_params
    params.permit(:product_id, :quantity)
  end

  def cart_product_update_params
    params.permit(:quantity)
  end

  def load_cart_product
    @cart_product = CartProduct.find(params[:id])
  end

  def calculate_price(cart_product, quantity)
    cart_product.price * quantity
  end

  def destroy_cart_product
    @cart_product.destroy
    redirect_to cart_products_path, notice: '商品をカートから削除しました。'
  end

  def save_and_redirect(cart_product, notice, redirect_path)
    if cart_product.save
      redirect_to(redirect_path, notice:)
    else
      redirect_to redirect_path, notice: '操作を完了できませんでした。'
    end
  end
end

app/helpers/cart_products_helper.rb
# frozen_string_literal: true

module CartProductsHelper
end

app/views/cart_products/index.html.erb
<div class="container">
  <main>
    <div class="py-5 text-center">
      <h2>注文内容</h2>
    </div>
    <div class="row g-5">
      <div class="col-md-5 col-lg-4 order-md-last">
        <h4 class="d-flex justify-content-between align-items-center mb-3">
          <span class="text-primary">買い物かご</span>
          <span class="badge bg-primary rounded-pill"><%= @current_cart.cart_products.sum(:quantity) %></span>
        </h4>
        <ul class="list-group mb-3">
          <% if @current_cart.cart_products.empty? %>
            <p>カートに何も入っていません</p>
          <% else %>
            <% @current_cart.cart_products.order(:product_id).each do |cart_product| %>
              <li class="list-group-item d-flex justify-content-between lh-sm">
                <div>
                  <h6 class = "my-0 fs-5 fw-medium mb-2"><%= cart_product.name %></h6>
                  <div class="">
                    <%= form_with model: @cart_product, url: cart_product_path(cart_product), method: :patch, class: "d-flex col-md-10" do | form | %>
                      <%= form.number_field :quantity, min: 0, class: 'form-control text-center me-1', value: cart_product.quantity %>
                      <%= form.submit '更新', class: 'btn btn-outline-dark me-1' %>
                      <%= link_to '削除', cart_product_path(cart_product), data: { turbo_method: :delete, turbo_confirm: '削除しますか？' }, class: 'btn btn-outline-dark text-nowrap' %>
                    <% end %>
                  </div>
                </div>
                <span class="text-body-secondary  text-nowrap"><%= cart_product.total_price %>円</span>
              </li>
            <% end %>
          <% end %>
          <% if @discounted_price %>
            <li class="list-group-item d-flex justify-content-between bg-body-tertiary">
              <div class="text-success">
                <h6 class="my-0">プロモーションコード</h6>
              </div>
              <span class="text-success">−<%= @current_cart.promotion.discount_price%>円</span>
            </li>
          <% end %>
          <% if @discounted_price %>
            <li class="list-group-item d-flex justify-content-between">
              <span>合計</span>
              <strong><%= @discounted_price %>円</strong>
            </li>
          <% else %>
            <li class="list-group-item d-flex justify-content-between">
              <span>合計</span>
              <strong><%= @current_cart.cart_products.sum(:total_price) %>円</strong>
            </li>
          <% end %>
        </ul>
        <%= form_with url: promotion_path(@current_cart), method: :patch, scope: :promotion, class: 'card p-2' do | form | %>
          <div class="input-group">
            <%= form.text_field :code, class: 'form-control', placeholder: 'プロモーションコード' %>
            <%= form.submit '適用', class: 'btn btn-secondary' %>
          </div>
        <% end %>
      </div>
      <div class="col-md-7 col-lg-8">
        <h4 class="mb-3">請求先住所</h4>
        <%= form_with model: @order , url: cart_orders_path(@current_cart), local: true do | form | %>
          <div class="row g-3">
            <div class="col-sm-6">
              <%= form.label :last_name, "姓", class: 'form-label' %>
              <%= form.text_field :last_name, placeholder: '田中', class: 'form-control', required: true %>
              <% if @order.errors.include?(:last_name) %>
                <div class="alert alert-danger mt-3">
                  <ul class="mb-0">
                    <% @order.errors.full_messages_for(:last_name).each do |message|  %>
                      <li>
                        <%= message %>
                      </li>
                    <% end %>
                  </ul>
                </div>
              <% end %>
            </div>
            <div class="col-sm-6">
              <%= form.label :first_name, "名", class: 'form-label' %>
              <%= form.text_field :first_name, placeholder: '太郎', class: 'form-control', required: true %>
              <% if @order.errors.include?(:first_name) %>
                <div class="alert alert-danger mt-3">
                  <ul class="mb-0">
                    <% @order.errors.full_messages_for(:first_name).each do |message|  %>
                      <li>
                        <%= message %>
                      </li>
                    <% end %>
                  </ul>
                </div>
              <% end %>
            </div>
            <div class="col-12">
              <%= form.label :email, "メールアドレス", class: 'form-label' %>
              <%= form.text_field :email, placeholder: 'you@exmaple.com', class: 'form-control', required: true %>
              <% if @order.errors.include?(:email) %>
                <div class="alert alert-danger mt-3">
                  <ul class="mb-0">
                    <% @order.errors.full_messages_for(:email).each do |message|  %>
                      <li>
                        <%= message %>
                      </li>
                    <% end %>
                  </ul>
                </div>
              <% end %>
            </div>
            <div class="col-3">
              <%= form.label :postal_code, "郵便番号", class: 'form-label' %>
              <%= form.text_field :postal_code, placeholder: '012-3456', class: 'form-control', required: true %>
              <% if @order.errors.include?(:postal_code) %>
                <div class="alert alert-danger mt-3">
                  <ul class="mb-0">
                    <% @order.errors.full_messages_for(:postal_code).each do |message|  %>
                      <li>
                        <%= message %>
                      </li>
                    <% end %>
                  </ul>
                </div>
              <% end %>
            </div>
            <div class="col-6">
              <%= form.label :country, "国", class: 'form-label' %>
              <%= form.text_field :country, placeholder: '日本', class: 'form-control', required: true %>
              <% if @order.errors.include?(:country) %>
                <div class="alert alert-danger mt-3">
                  <ul class="mb-0">
                    <% @order.errors.full_messages_for(:country).each do |message|  %>
                      <li>
                        <%= message %>
                      </li>
                    <% end %>
                  </ul>
                </div>
              <% end %>
            </div>
            <div class="col-3">
              <%= form.label :prefecture, "都道府県", class: 'form-label' %>
              <%= form.text_field :prefecture, placeholder: '東京都', class: 'form-control', required: true %>
              <% if @order.errors.include?(:prefecture) %>
                <div class="alert alert-danger mt-3">
                  <ul class="mb-0">
                    <% @order.errors.full_messages_for(:prefecture).each do |message|  %>
                      <li>
                        <%= message %>
                      </li>
                    <% end %>
                  </ul>
                </div>
              <% end %>
            </div>
            <div class="col-12">
              <%= form.label :address_one, "住所1", class: 'form-label' %>
              <%= form.text_field :address_one, placeholder: '新宿西新宿', class: 'form-control', required: true %>
              <% if @order.errors.include?(:address_one) %>
                <div class="alert alert-danger mt-3">
                  <ul class="mb-0">
                    <% @order.errors.full_messages_for(:address_one).each do |message|  %>
                      <li>
                        <%= message %>
                      </li>
                    <% end %>
                  </ul>
                </div>
              <% end %>
            </div>
            <div class="col-12">
              <%= form.label :address_two, "住所2", class: 'form-label' %>
              <%= form.text_field :address_two, placeholder: '1-2-3', class: 'form-control', required: true %>
              <% if @order.errors.include?(:address_two) %>
                <div class="alert alert-danger mt-3">
                  <ul class="mb-0">
                    <% @order.errors.full_messages_for(:address_two).each do |message|  %>
                      <li>
                        <%= message %>
                      </li>
                    <% end %>
                  </ul>
                </div>
              <% end %>
            </div>
          </div>
          <hr class="my-4">
          <h4 class="mb-3">クレジットカード情報</h4>
          <div class="row gy-3">
            <div class="col-md-6">
              <%= form.label :credit_name, "名義", class: 'form-label' %>
              <%= form.text_field :credit_name, placeholder: 'TANAKA TARO', class: 'form-control', required: true %>
              <% if @order.errors.include?(:credit_name) %>
                <div class="alert alert-danger mt-3">
                  <ul class="mb-0">
                    <% @order.errors.full_messages_for(:credit_name).each do |message|  %>
                      <li>
                        <%= message %>
                      </li>
                    <% end %>
                  </ul>
                </div>
              <% end %>
            </div>
            <div class="col-md-6">
              <%= form.label :credit_number, "カード番号", class: 'form-label' %>
              <%= form.text_field :credit_number, placeholder: '0000-1111-2222-3333', class: 'form-control', required: true %>
              <% if @order.errors.include?(:credit_number) %>
                <div class="alert alert-danger mt-3">
                  <ul class="mb-0">
                    <% @order.errors.full_messages_for(:credit_number).each do |message|  %>
                      <li>
                        <%= message %>
                      </li>
                    <% end %>
                  </ul>
                </div>
              <% end %>
            </div>
            <div class="col-md-3">
              <%= form.label :credit_expiration, "有効期限", class: 'form-label' %>
              <%= form.text_field :credit_expiration, placeholder: '03/28', class: 'form-control', required: true %>
              <% if @order.errors.include?(:credit_expiration) %>
                <div class="alert alert-danger mt-3">
                  <ul class="mb-0">
                    <% @order.errors.full_messages_for(:credit_expiration).each do |message|  %>
                      <li>
                        <%= message %>
                      </li>
                    <% end %>
                  </ul>
                </div>
              <% end %>
            </div>
            <div class="col-md-3">
              <%= form.label :credit_cvv, "CVV", class: 'form-label' %>
              <%= form.text_field :credit_cvv, placeholder: '012', class: 'form-control', required: true %>
              <% if @order.errors.include?(:credit_cvv) %>
                <div class="alert alert-danger mt-3">
                  <ul class="mb-0">
                    <% @order.errors.full_messages_for(:credit_cvv).each do |message|  %>
                      <li>
                        <%= message %>
                      </li>
                    <% end %>
                  </ul>
                </div>
              <% end %>
            </div>
          </div>
          <hr class="my-4">
          <%= form.submit '購入する', class: 'w-100 btn btn-primary btn-lg mb-5' %>
        <% end %>
      </div>
    </div>
  </main>
</div>