config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'products#index'
  namespace :admin do
    resources :products
  end
  resources :products do
    resources :cart_products, only: :create
  end
  resources :cart_products, only: %i[index update destroy]
  resources :carts do
    resources :orders, only: %i[create show]
  end
  resources :orders, only: %i[index]
  resources :promotions, only: %i[update]
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  belongs_to :cart
  has_many :order_products, dependent: :destroy
  after_save :after_order_save

  validates :first_name, :last_name, :country, :prefecture, :address_one, :address_two, :credit_expiration,
            presence: true
  validates :email, presence: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i, message: 'の形式が正しくありません。' }
  validates :postal_code, presence: true, format: { with: /\A\d{3}-?\d{4}\z/, message: 'の形式が正しくありません。' }
  validates :credit_name, presence: true, format: { with: /\A[A-Z\s-]+\z/, message: 'の形式が正しくありません。' }
  validates :credit_number, presence: true, format: { with: /\A(\d{4}-?){3}\d{4}\z/, message: 'の形式が正しくありません。' }
  validate :credit_expiration_must_be_valid
  validates :credit_cvv, presence: true, format: { with: /\A\d{3,4}\z/, message: 'の形式が正しくありません。3桁または4桁の数字を入力してください。' }

  def credit_expiration_must_be_valid
    return if credit_expiration.blank?

    unless credit_expiration.match(%r{\A(0[1-9]|1[0-2])/([0-9]{2})\z})
      errors.add(:credit_expiration, 'の形式が正しくありません。MM/YYの形式で入力してください。。')
      return
    end

    month, year = credit_expiration.split('/').map(&:to_i)
    expiration_date = Date.new(year + 2000, month, -1)

    return unless expiration_date < Time.zone.today.beginning_of_month

    errors.add(:credit_expiration, 'が切れています。')
  end

  private

  def after_order_save
    create_order_products
    OrderMailer.ordered_email(self).deliver_now
  end

  def create_order_products
    cart.cart_products.each do |cart_product|
      order_products.create(
        name: cart_product.product.name,
        price: cart_product.product.price,
        total_price: cart_product.product.price * cart_product.quantity,
        quantity: cart_product.quantity
      )
    end
  end
end

app/controllers/orders_controller.rb
# frozen_string_literal: true

class OrdersController < ApplicationController
  before_action :basic_auth, only: %i[index show]

  def index
    @orders = Order.all.order(created_at: :desc)
  end

  def show
    @order = Order.find(params[:id])
  end

  def create
    @order = Order.new(order_params)
    if @order.save
      clear_cart
      redirect_to root_path, notice: '購入が完了しました。メールをご確認ください。'
    else
      render 'cart_products/index', status: :unprocessable_entity
    end
  end

  private

  def order_params
    params.require(:order).permit(
      :first_name,
      :last_name,
      :email,
      :postal_code,
      :country,
      :prefecture,
      :address_one,
      :address_two,
      :credit_number,
      :credit_name,
      :credit_cvv,
      :credit_expiration
    )
          .merge(cart_id: params[:cart_id])
  end

  def clear_cart
    reset_session
  end
end

app/helpers/orders_helper.rb
# frozen_string_literal: true

module OrdersHelper
end

app/views/orders/index.html.erb
<header class="bg-primary py-5">
  <div class="container px-4 px-lg-5 my-5">
    <div class="text-center text-white">
      <h1 class="display-4 fw-bolder">購入履歴</h1>
      <p class="lead fw-normal text-white-50 mb-0">管理画面</p>
    </div>
  </div>
</header>
<div class="container px-4 px-lg-5 mt-5 mb-5">
  <table class="table table-striped table-bordered mb-0">
    <thead>
      <tr>
        <th scope="col">No</th>
        <th scope="col">顧客名</th>
        <th scope="col">総額（円）</th>
        <th scope="col">購入日時</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% @orders.each do |order| %>
        <tr>
          <td style="vertical-align: middle;"><%= order.id %></td>
          <td style="vertical-align: middle;"><%= order.last_name %><%= order.first_name %></td>
          <% if order.cart.promotion %>
            <td style="vertical-align: middle;"><%= [order.order_products.sum(:total_price) - order.cart.promotion.discount_price, 0].max %></td>
          <% else %>
            <td style="vertical-align: middle;"><%= order.order_products.sum(:total_price) %></td>
          <% end %>
          <td style="vertical-align: middle;"><%= order.created_at.strftime('%Y年%m月%d日 %H:%M') %></td>
          <td style="vertical-align: middle;"><%= link_to '詳細', cart_order_path(order.cart, order), class: 'btn btn-outline-dark' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/orders/show.html.erb
<header class="bg-primary py-5">
  <div class="container px-4 px-lg-5 my-5">
    <div class="text-center text-white">
      <h1 class="display-4 fw-bolder">購入明細</h1>
      <p class="lead fw-normal text-white-50 mb-0">管理画面</p>
    </div>
  </div>
</header>
<div class="container px-4 px-lg-5 mt-5 mb-5">
  <%# <h2>購入内容</h2> %>
  <p>■購入者：<%= @order.last_name %><%= @order.first_name %> 様</p>
  <p>■配送先住所：〒<%= @order.postal_code %> <%= @order.country %> <%= @order.prefecture %> <%= @order.address_one %> <%= @order.address_two %></p>
  <p>■支払い方法：クレジットカード</p>
  <ul>
    <li>名義：<%= @order.credit_name %></li>
    <li>番号：<%= @order.credit_number %></li>
    <li>有効期限：<%= @order.credit_expiration %></li>
    <li>セキュリティコード：<%= @order.credit_cvv %></li>
  </ul>
  <p>■購入日時：<%= @order.created_at.strftime('%Y年%m月%d日 %H:%M') %></p>
  <table class="table table-striped table-bordered mb-2">
    <thead>
      <tr>
        <th scope="col">No</th>
        <th scope="col">商品名</th>
        <th scope="col">金額（円）</th>
        <th scope="col">個数</th>
        <th scope="col">合計金額（円）</th>
      </tr>
    </thead>
    <tbody>
      <% @order.order_products.each_with_index do |order_product, index| %>
        <tr>
          <td style="vertical-align: middle;"><%= index + 1 %></td>
          <td style="vertical-align: middle;"><%= order_product.name %></td>
          <td style="vertical-align: middle;"><%= order_product.price %></td>
          <td style="vertical-align: middle;"><%= order_product.quantity %></td>
          <td style="vertical-align: middle;"><%= order_product.total_price %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="d-flex justify-content-end">
    <% if @order.cart.promotion %>
      <div>
        <p class="h4" >■小計：<%= @order.order_products.sum(:total_price) %>円</p>
        <p class="h4">■割引額：-<%= @order.cart.promotion.discount_price %>円</p>
        <p class="h4">■総額：<%= [@order.order_products.sum(:total_price) - @order.cart.promotion.discount_price, 0].max %>円</p>
      </div>
    <% else %>
      <div>
        <p class="h4">■総額：<%= @order.order_products.sum(:total_price) %>円</p>
      </div>
    <% end %>
  </div>
</div>