config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'products#index'
  namespace :admin do
    resources :products
  end
  resources :products do
    resources :cart_products, only: :create
  end
  resources :cart_products, only: %i[index update destroy]
  resources :carts do
    resources :orders, only: %i[create show]
  end
  resources :orders, only: %i[index]
  resources :promotions, only: %i[update]
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  has_many :cart_products, dependent: :destroy
  has_one_attached :image
  validates :name, :image, :description, presence: true
  validates :price, presence: true,
                    numericality: { only_integer: true, greater_than_or_equal_to: 0, message: 'を0以上の半角整数で入力してください' }
  validates :evaluation, presence: true, numericality: { only_integer: true, in: 1..5, message: 'を1〜5の半角整数で入力してください' }
end

app/controllers/admin/products_controller.rb
# frozen_string_literal: true

module Admin
  class ProductsController < ApplicationController
    before_action :basic_auth
    before_action :load_product, only: %i[show edit update destroy]

    def index
      @products = Product.all.order(:id)
    end

    def show; end

    def new
      @product = Product.new
    end

    def create
      @product = Product.new(product_params)
      if @product.save
        redirect_to admin_products_path, notice: '商品を追加しました'
      else
        render :new, status: :unprocessable_entity
      end
    end

    def edit; end

    def update
      if @product.update(product_params)
        redirect_to admin_products_path, notice: "#{@product.name}を更新しました"
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @product.destroy
      redirect_to admin_products_path, notice: "#{@product.name}を削除しました", status: :see_other
    end

    private

    def product_params
      params.require(:product).permit(:name, :price, :evaluation, :image, :description)
    end

    def load_product
      @product = Product.find(params[:id])
    end
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  def index
    @products = Product.all.order(:id)
  end

  def show
    @product = Product.find(params[:id])
    @related_products = Product.where.not(id: @product.id).order(created_at: :desc).limit(4)
  end
end

app/helpers/admin/products_helper.rb
# frozen_string_literal: true

module Admin
  module ProductsHelper
  end
end

app/views/products/_list.html.erb
<% products.each do |product| %>
  <div class="col mb-5">
    <div class="card h-100">
      <%= image_tag product.image, class:'card-img-top', style: 'height: 150px; object-fit: cover;' %>
      <div class="card-body p-4">
        <div class="text-center">
          <h5 class="fw-bolder"><%= product.name %></h5>
          <div class="d-flex justify-content-center small text-warning mb-2">
            <% product.evaluation.times do %>
              <div class="bi-star-fill"></div>
            <% end %>
          </div>
          <%= "#{product.price}円" %>
        </div>
      </div>
      <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
        <div class="text-center">
          <% if request.path_info == '/' %>
            <%= link_to '詳細', product, class: 'btn btn-outline-dark mb-2' %>
            <%= button_to 'カートに入れる', product_cart_products_path(product.id), class: 'btn btn-outline-dark mt-auto' %>
          <% end %>
          <% if request.path_info.start_with?('/admin') %>
            <%= link_to '詳細', admin_product_path(product), class: 'btn btn-outline-dark mt-auto' %>
            <%= link_to '編集', edit_admin_product_path(product), class: 'btn btn-outline-dark mt-auto' %>
            <%= link_to '削除', admin_product_path(product), data: { turbo_method: :delete, turbo_confirm: '削除しますか？' }, class: 'btn btn-outline-dark mt-auto' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/products/_product_show.html.erb
<div class="row gx-4 gx-lg-5 align-items-center">
  <div class="col-md-6"><%= image_tag product.image, class:'card-img-top mb-5 mb-md-0' %></div>
  <div class="col-md-6">
    <h1 class="display-5 fw-bolder"><%= product.name %></h1>
    <div class="fs-5 mb-5">
      <span><%= product.price %>円</span>
    </div>
    <p class="lead"><%= product.description %></p>
    <div class="d-flex">
      <% if request.path_info.start_with?('/products') %>
        <%= form_with url: product_cart_products_path(product.id) do | form | %>
          <%= form.number_field :quantity, min: 1, class: 'form-control text-center me-3', value: 1 %>
          <%= form.submit 'カートに入れる', class: 'btn btn-outline-dark flex-shrink-0' %>
        <% end %>
      <% end %>
      <% if request.path_info.start_with?('/admin') %>
        <%= link_to '編集', edit_admin_product_path(product), class: 'btn btn-outline-dark mt-auto' %>
      <% end %>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<!-- Header-->
<header class="bg-dark py-5">
  <div class="container px-4 px-lg-5 my-5">
    <div class="text-center text-white">
      <h1 class="display-4 fw-bolder">Shop in style</h1>
      <p class="lead fw-normal text-white-50 mb-0">With this shop hompeage template</p>
    </div>
  </div>
</header>
<!-- Section-->
<section class="py-5">
  <div class="container px-4 px-lg-5 mt-5">
    <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
      <%= render partial: 'list', locals: { products: @products} %>
    </div>
  </div>
</section>

app/views/products/show.html.erb
<section class="py-5">
  <div class="container px-4 px-lg-5 my-5">
    <%= render partial: 'product_show', locals: { product: @product} %>
  </div>
</section>
<!-- Related items section-->
<section class="py-5 bg-light">
  <div class="container px-4 px-lg-5 mt-5">
    <h2 class="fw-bolder mb-4">関連商品</h2>
    <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
      <%= render partial: 'list', locals: { products: @related_products} %>
    </div>
  </div>
</section>