config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'products#index'
  namespace :admin do
    resources :products
  end
  resources :products do
    resources :cart_products, only: :create
  end
  resources :cart_products, only: %i[index update destroy]
  resources :carts do
    resources :orders, only: %i[create show]
  end
  resources :orders, only: %i[index]
  resources :promotions, only: %i[update]
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/views/layouts/_footer.html.erb
<!-- Footer-->
<footer class="py-5 bg-dark">
  <div class="container">
    <p class="m-0 text-center text-white">Copyright &copy; Rails EC 2024</p>
  </div>
</footer>

app/views/layouts/_nav.html.erb
        <!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container px-4 px-lg-5">
    <%= link_to 'Rails EC', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
        <li class="nav-item"><a class="nav-link active" aria-current="page" href="#!">Home</a></li>
        <li class="nav-item"><a class="nav-link" href="#!">About</a></li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Shop</a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#!">All Products</a></li>
            <li><hr class="dropdown-divider" /></li>
            <li><a class="dropdown-item" href="#!">Popular Items</a></li>
            <li><a class="dropdown-item" href="#!">New Arrivals</a></li>
          </ul>
        </li>
      </ul>
      <div class="d-flex gap-3">
        <%= link_to '管理トップ', admin_products_path, class: 'btn btn-outline-dark mr-3' %>
        <%= link_to '新規追加', new_admin_product_path, class: 'btn btn-outline-dark mr-3' %>
        <%= link_to '購入履歴', orders_path, class: 'btn btn-outline-dark mr-3' %>
        <%= link_to cart_products_path, class: 'btn btn-outline-dark mr-2' do %>
          <i class="bi-cart-fill me-1"></i>
          <span>カート</span>
          <span class="badge bg-dark text-white ms-1 rounded-pill"><%= @current_cart.cart_products.sum(:quantity) %></span>
        <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails EC</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body>
    <%# nav %>
    <%= render 'layouts/nav' %>
    <% if flash.notice.present? %>
      <div class="alert alert-primary mb-0 text-center" role="alert">
        <%= flash.notice %>
      </div>
    <% end %>
    <%= yield %>
    <%# footer %>
    <%= render 'layouts/footer' %>
  </body>
</html>